version: '3.7'
services:

  #PHP & Apache
  php-goods:
    build:
      context: .docker/services
      dockerfile: php/Dockerfile
    volumes:
      - "./:/var/www/html"
      - ".docker/services/php/local.ini:/usr/local/etc/php/conf.d/local.ini"
    environment:
      DB_NAME: ${DB_DATABASE}
      DB_USER: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${APP_PORT}:80"

  #DB service
  mariadb:
    image: mariadb:10.5.4
    volumes:
      - "db:/var/lib/mysql"
      - ".docker/services/mariadb/my.cnf:/etc/mysql/my.cnf"


    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"

#Volumes
volumes:
  db:


